# list all message

# # Create new message
# POST http://localhost:3000/messages
# content-type: application/json

# {
#   "content": "HelloWorld"
# }



# GET http://localhost:3000/messages 




# Get a specific message by ID
GET http://localhost:3000/messages/43