# list all message


# Create new message
POST http://localhost:3000/messages
Content-Type: application/json

{
  "text": "Hello, World!"
}


GET http://localhost:3000/messages 





# Get a specific message by ID
GET http://localhost:3000/messages/{id}